config/routes.rb
Rails.application.routes.draw do
  resources :flags
  resources :commands

  # repositories
  post "/create_repository", to: "repositories#create_repository"
  get "/get_repository", to: "repositories#get_repository"
  post "/upload", to: "repositories#upload_project_to_repository"

  # files
  post "/upload_file", to: "files#upload_file"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/flag.rb
class Flag < ApplicationRecord
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
  before_action :set_flag, only: %i[ show edit update destroy ]

  # GET /flags or /flags.json
  def index
    @flags = Flag.all
  end

  # GET /flags/1 or /flags/1.json
  def show
  end

  # GET /flags/new
  def new
    @flag = Flag.new
  end

  # GET /flags/1/edit
  def edit
  end

  # POST /flags or /flags.json
  def create
    @flag = Flag.new(flag_params)

    respond_to do |format|
      if @flag.save
        format.html { redirect_to flag_url(@flag), notice: "Flag was successfully created." }
        format.json { render :show, status: :created, location: @flag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flags/1 or /flags/1.json
  def update
    respond_to do |format|
      if @flag.update(flag_params)
        format.html { redirect_to flag_url(@flag), notice: "Flag was successfully updated." }
        format.json { render :show, status: :ok, location: @flag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flags/1 or /flags/1.json
  def destroy
    @flag.destroy

    respond_to do |format|
      format.html { redirect_to flags_url, notice: "Flag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flag
      @flag = Flag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flag_params
      params.require(:flag).permit(:name, :value)
    end
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/views/flags/_flag.html.erb
<div id="<%= dom_id flag %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= flag.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Value:</strong>
    <%= flag.value %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this flag", flag, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this flag', edit_flag_path(flag), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/flags/_form.html.erb
<%= form_with(model: flag, class: "contents") do |form| %>
  <% if flag.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(flag.errors.count, "error") %> prohibited this flag from being saved:</h2>

      <ul>
        <% flag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :value %>
    <%= form.text_field :value, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/flags/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing flag</h1>

  <%= render "form", flag: @flag %>

  <%= link_to "Show this flag", @flag, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to flags", flags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/flags/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Flags</h1>
    <%= link_to 'New flag', new_flag_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="flags" class="min-w-full">
    <%= render @flags %>
  </div>
</div>

app/views/flags/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New flag</h1>

  <%= render "form", flag: @flag %>

  <%= link_to 'Back to flags', flags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/flags/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @flag %>

    <%= link_to 'Edit this flag', edit_flag_path(@flag), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this flag', flag_path(@flag), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to flags', flags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>