config/routes.rb
Rails.application.routes.draw do
  resources :flags
  resources :commands

  # repositories
  post "/create_repository", to: "repositories#create_repository"
  get "/get_repository", to: "repositories#get_repository"
  post "/upload", to: "repositories#upload_project_to_repository"

  # files
  post "/upload_file", to: "files#upload_file"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/command.rb
class Command < ApplicationRecord
  def run_command(command, flags, final_path, path, timestamp)
    command_string = create_command(command, flags)
    RunCommand.perform_async([command_string], final_path, path, timestamp, false)
  end

  def create_command(command, flags)
    # create command string
    command_string = command.name

    # add flags
    flags.each do |flag|
      command_string += " #{flag}"
    end

    command_string
  end
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: %i[ show edit update destroy ]

  # GET /commands or /commands.json
  def index
    @commands = Command.all
  end

  # GET /commands/1 or /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands or /commands.json
  def create
    @command = Command.new(command_params)

    flags = params[:flags]

    @command.flags = flags

    # Command.new.delay.run_command(@command, flags)
    # execute = run_command(@command, flags)

    respond_to do |format|
      if @command.save
        final_path = "/home/"
        path = "./home/"
        timestamp = Time.now.to_i
        @command.run_command(@command, flags, final_path, final_path, timestamp)
        created_path = final_path
        format.html { redirect_to command_url(@command), notice: "Command was successfully created." }
        # send the created path to the json response
        format.json { render json: { path: created_path } }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1 or /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to command_url(@command), notice: "Command was successfully updated." }
        format.json { render :show, status: :ok, location: @command }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1 or /commands/1.json
  def destroy
    @command.destroy

    respond_to do |format|
      format.html { redirect_to commands_url, notice: "Command was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_command
    @command = Command.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def command_params
    params.require(:command).permit(:name, :is_available, :requires_admin)
  end

  def run_command_by_id(id)
    system(create_command(Command.find(id)))
  end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_command.html.erb
<div id="<%= dom_id command %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= command.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Flags:</strong>
    <%= command.flags.join("\n") %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Is available:</strong>
    <%= command.is_available %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Requires admin:</strong>
    <%= command.requires_admin %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this command", command, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this command', edit_command_path(command), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/commands/_form.html.erb
<%= form_with(model: command, class: "contents") do |form| %>
  <% if command.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
        <% command.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  
  <div class="my-5">
    <%= form.label :flags %>
    <%= form.text_field :flags, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :is_available %>
    <%= form.check_box :is_available, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :requires_admin %>
    <%= form.check_box :requires_admin, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/commands/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing command</h1>

  <%= render "form", command: @command %>

  <%= link_to "Show this command", @command, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to commands", commands_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/commands/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Commands</h1>
    <%= link_to 'New command', new_command_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="commands" class="min-w-full">
    <%= render @commands %>
  </div>
</div>

app/views/commands/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New command</h1>

  <%= render "form", command: @command %>

  <%= link_to 'Back to commands', commands_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/commands/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @command %>

    <%= link_to 'Edit this command', edit_command_path(@command), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this command', command_path(@command), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to commands', commands_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>